steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world-app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hello-world-app:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'hello-world-app', '--image', 'gcr.io/$PROJECT_ID/hello-world-app:${SHORT_SHA}', '--region', 'us-central1', '--platform', 'managed', "--allow-unauthenticated"]
